-- GRAVTY-style guided flow fields for offers.
ALTER TABLE reward_offers ADD COLUMN IF NOT EXISTS subtitle VARCHAR(255);
ALTER TABLE reward_offers ADD COLUMN IF NOT EXISTS all_locations BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE reward_offers ADD COLUMN IF NOT EXISTS billing_type VARCHAR(32) NOT NULL DEFAULT 'BILLING_SPONSOR';
ALTER TABLE reward_offers ADD COLUMN IF NOT EXISTS billing_sponsor_id BIGINT;
ALTER TABLE reward_offers ADD COLUMN IF NOT EXISTS member_visibility BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE reward_offers ADD COLUMN IF NOT EXISTS offer_visibility VARCHAR(32) NOT NULL DEFAULT 'ON_OFFER_LAUNCH';
ALTER TABLE reward_offers ADD COLUMN IF NOT EXISTS max_reward_limit_points BIGINT;
ALTER TABLE reward_offers ADD COLUMN IF NOT EXISTS requires_acceptance BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE reward_offers ADD COLUMN IF NOT EXISTS target_account VARCHAR(32) NOT NULL DEFAULT 'REDEMPTION';
ALTER TABLE reward_offers ADD COLUMN IF NOT EXISTS fulfillment_type VARCHAR(32);

CREATE TABLE IF NOT EXISTS reward_offer_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    CONSTRAINT uk_reward_offer_location UNIQUE (offer_id, location_id)
);

CREATE TABLE IF NOT EXISTS reward_offer_kpis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id BIGINT NOT NULL,
    kpi_code VARCHAR(64) NOT NULL,
    target_value NUMERIC(19, 2) NOT NULL DEFAULT 0,
    CONSTRAINT uk_reward_offer_kpi UNIQUE (offer_id, kpi_code)
);
