-- Migrates legacy string-keyed tables to the current Long-based JPA model.
-- Safe to run only while these tables are empty (they are seeded at runtime).

BEGIN;

-- reward_tenants
ALTER TABLE reward_tenants ALTER COLUMN id DROP DEFAULT;
ALTER TABLE reward_tenants ALTER COLUMN id TYPE bigint USING NULLIF(id, '')::bigint;
ALTER TABLE reward_tenants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- reward_programs
ALTER TABLE reward_programs ALTER COLUMN id DROP DEFAULT;
ALTER TABLE reward_programs ALTER COLUMN id TYPE bigint USING NULLIF(id, '')::bigint;
ALTER TABLE reward_programs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE reward_programs ALTER COLUMN tenant_id TYPE bigint USING NULLIF(tenant_id, '')::bigint;

-- reward_members
ALTER TABLE reward_members ALTER COLUMN id DROP DEFAULT;
ALTER TABLE reward_members ALTER COLUMN id TYPE bigint USING NULLIF(id, '')::bigint;
ALTER TABLE reward_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE reward_members ALTER COLUMN tenant_id TYPE bigint USING NULLIF(tenant_id, '')::bigint;

-- reward_accounts
ALTER TABLE reward_accounts ALTER COLUMN id DROP DEFAULT;
ALTER TABLE reward_accounts ALTER COLUMN id TYPE bigint USING NULLIF(id, '')::bigint;
ALTER TABLE reward_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE reward_accounts ALTER COLUMN tenant_id TYPE bigint USING NULLIF(tenant_id, '')::bigint;
ALTER TABLE reward_accounts ALTER COLUMN member_id TYPE bigint USING NULLIF(member_id, '')::bigint;

-- reward_transactions
ALTER TABLE reward_transactions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE reward_transactions ALTER COLUMN id TYPE bigint USING NULLIF(id, '')::bigint;
ALTER TABLE reward_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE reward_transactions ALTER COLUMN tenant_id TYPE bigint USING NULLIF(tenant_id, '')::bigint;
ALTER TABLE reward_transactions ALTER COLUMN member_id TYPE bigint USING NULLIF(member_id, '')::bigint;
ALTER TABLE reward_transactions ALTER COLUMN account_id TYPE bigint USING NULLIF(account_id, '')::bigint;

-- reward_wallet_history
ALTER TABLE reward_wallet_history ALTER COLUMN id DROP DEFAULT;
ALTER TABLE reward_wallet_history ALTER COLUMN id TYPE bigint USING NULLIF(id, '')::bigint;
ALTER TABLE reward_wallet_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE reward_wallet_history ALTER COLUMN tenant_id TYPE bigint USING NULLIF(tenant_id, '')::bigint;
ALTER TABLE reward_wallet_history ALTER COLUMN member_id TYPE bigint USING NULLIF(member_id, '')::bigint;
ALTER TABLE reward_wallet_history ALTER COLUMN account_id TYPE bigint USING NULLIF(account_id, '')::bigint;

COMMIT;
