BEGIN;

CREATE TABLE IF NOT EXISTS reward_member_import_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'QUEUED',
    file_name VARCHAR(255) NOT NULL,
    storage_path VARCHAR(1024) NOT NULL,
    total_records BIGINT NOT NULL DEFAULT 0,
    processed_records BIGINT NOT NULL DEFAULT 0,
    imported_records BIGINT NOT NULL DEFAULT 0,
    duplicate_records BIGINT NOT NULL DEFAULT 0,
    failed_records BIGINT NOT NULL DEFAULT 0,
    error_file_path VARCHAR(1024),
    error_summary VARCHAR(4000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_reward_member_import_jobs_tenant_created
    ON reward_member_import_jobs (tenant_id, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uk_reward_members_tenant_external_user
    ON reward_members (tenant_id, external_user_id);

CREATE UNIQUE INDEX IF NOT EXISTS uk_reward_accounts_tenant_member_type
    ON reward_accounts (tenant_id, member_id, account_type);

COMMIT;