-- 1) reward_sponsors: add sponsor_type used by new code
ALTER TABLE reward_sponsors
ADD COLUMN IF NOT EXISTS sponsor_type VARCHAR(32);

UPDATE reward_sponsors
SET sponsor_type = 'CHILD'
WHERE sponsor_type IS NULL OR sponsor_type = '';

UPDATE reward_sponsors
SET sponsor_type = 'HOST'
WHERE sponsor_type = 'CHILD' AND sponsor_code LIKE 'HOST_%';

ALTER TABLE reward_sponsors
ALTER COLUMN sponsor_type SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'chk_reward_sponsors_type'
  ) THEN
    ALTER TABLE reward_sponsors
    ADD CONSTRAINT chk_reward_sponsors_type
    CHECK (sponsor_type IN ('HOST','CHILD','PARTNER'));
  END IF;
END $$;

-- 2) reward_sponsor_locations: add location_pin + uniqueness
ALTER TABLE reward_sponsor_locations
ADD COLUMN IF NOT EXISTS location_pin VARCHAR(64);

UPDATE reward_sponsor_locations
SET location_pin = location_code
WHERE location_pin IS NULL OR location_pin = '';

ALTER TABLE reward_sponsor_locations
ALTER COLUMN location_pin SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'uk_reward_locations_tenant_sponsor_code'
  ) THEN
    ALTER TABLE reward_sponsor_locations
    ADD CONSTRAINT uk_reward_locations_tenant_sponsor_code
    UNIQUE (tenant_id, sponsor_id, location_code);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'uk_reward_locations_tenant_sponsor_pin'
  ) THEN
    ALTER TABLE reward_sponsor_locations
    ADD CONSTRAINT uk_reward_locations_tenant_sponsor_pin
    UNIQUE (tenant_id, sponsor_id, location_pin);
  END IF;
END $$;

-- 3) reward_branches: switch from global code unique to tenant-scoped unique
DO $$
DECLARE c RECORD;
BEGIN
  FOR c IN
    SELECT conname
    FROM pg_constraint
    WHERE conrelid = 'reward_branches'::regclass
      AND contype = 'u'
      AND conname <> 'uk_reward_branches_tenant_code'
  LOOP
    BEGIN
      EXECUTE 'ALTER TABLE reward_branches DROP CONSTRAINT ' || quote_ident(c.conname);
    EXCEPTION WHEN others THEN
      NULL;
    END;
  END LOOP;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'uk_reward_branches_tenant_code'
  ) THEN
    ALTER TABLE reward_branches
    ADD CONSTRAINT uk_reward_branches_tenant_code
    UNIQUE (tenant_id, code);
  END IF;
END $$;

-- 4) new table: reward_partner_memberships
CREATE TABLE IF NOT EXISTS reward_partner_memberships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  sponsor_id BIGINT NOT NULL,
  member_id BIGINT NOT NULL,
  external_membership_id VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'uk_reward_partner_membership_external'
  ) THEN
    ALTER TABLE reward_partner_memberships
    ADD CONSTRAINT uk_reward_partner_membership_external
    UNIQUE (tenant_id, sponsor_id, external_membership_id);
  END IF;
END $$;

-- 5) new table: reward_reconciliation_batches
CREATE TABLE IF NOT EXISTS reward_reconciliation_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  sponsor_id BIGINT NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  point_cost NUMERIC(19,4) NOT NULL,
  total_points BIGINT NOT NULL DEFAULT 0,
  total_amount NUMERIC(19,2) NOT NULL DEFAULT 0,
  line_count INT NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 6) new table: reward_reconciliation_lines
CREATE TABLE IF NOT EXISTS reward_reconciliation_lines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id BIGINT NOT NULL,
  tenant_id BIGINT NOT NULL,
  sponsor_id BIGINT NOT NULL,
  transaction_id BIGINT NOT NULL,
  member_id BIGINT NOT NULL,
  points BIGINT NOT NULL,
  point_cost NUMERIC(19,4) NOT NULL,
  amount NUMERIC(19,2) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'uk_reward_recon_batch_txn'
  ) THEN
    ALTER TABLE reward_reconciliation_lines
    ADD CONSTRAINT uk_reward_recon_batch_txn
    UNIQUE (batch_id, transaction_id);
  END IF;
END $$;

-- 7) index for reconciliation batch generation query
CREATE INDEX IF NOT EXISTS idx_reward_txn_tenant_sponsor_type_created
ON reward_transactions (tenant_id, sponsor_id, transaction_type, created_at);

-- 8) Transaction safety: every supplied client reference can be processed once per operation type.
CREATE UNIQUE INDEX IF NOT EXISTS uk_reward_transactions_tenant_reference_type
ON reward_transactions (tenant_id, reference_id, transaction_type)
WHERE reference_id IS NOT NULL;

ALTER TABLE reward_transactions
ADD COLUMN IF NOT EXISTS original_transaction_id BIGINT;

-- 9) Rolling/fixed point-expiry policy and FIFO point-lot tracking.
ALTER TABLE reward_programs
ADD COLUMN IF NOT EXISTS expiry_type VARCHAR(20) NOT NULL DEFAULT 'ROLLING',
ADD COLUMN IF NOT EXISTS expiry_months INT NOT NULL DEFAULT 12,
ADD COLUMN IF NOT EXISTS expiry_warning_days INT NOT NULL DEFAULT 30;

ALTER TABLE reward_wallet_history
ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS expired_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS remaining_points BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_expired BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_reward_wallet_expiry
ON reward_wallet_history (tenant_id, expires_at)
WHERE account_type = 'REDEMPTION' AND entry_type = 'CREDIT' AND is_expired = FALSE AND remaining_points > 0;

-- 10) Four-category offer ecosystem: award, reward, privilege, and deal campaigns.
ALTER TABLE reward_offers
ADD COLUMN IF NOT EXISTS offer_code VARCHAR(100) NOT NULL DEFAULT 'LEGACY',
ADD COLUMN IF NOT EXISTS category VARCHAR(30) NOT NULL DEFAULT 'AWARD',
ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
ADD COLUMN IF NOT EXISTS max_total_claims INT,
ADD COLUMN IF NOT EXISTS total_claims_count INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_mto BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_featured BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS points_required BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS benefit_code VARCHAR(100),
ADD COLUMN IF NOT EXISTS target_tier_id BIGINT,
ADD COLUMN IF NOT EXISTS discount_type VARCHAR(30),
ADD COLUMN IF NOT EXISTS discount_value NUMERIC(19,4),
ADD COLUMN IF NOT EXISTS promo_code VARCHAR(100);

UPDATE reward_offers
SET offer_code = 'LEGACY-' || id
WHERE offer_code IS NULL OR offer_code = '' OR offer_code = 'LEGACY';

CREATE UNIQUE INDEX IF NOT EXISTS uk_reward_offers_tenant_code
ON reward_offers (tenant_id, offer_code);

CREATE INDEX IF NOT EXISTS idx_reward_offers_management
ON reward_offers (tenant_id, program_id, category, status, is_featured);

CREATE TABLE IF NOT EXISTS reward_offer_sponsors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  offer_id BIGINT NOT NULL,
  sponsor_id BIGINT NOT NULL,
  CONSTRAINT uk_reward_offer_sponsor UNIQUE (offer_id, sponsor_id)
);

CREATE TABLE IF NOT EXISTS reward_offer_target_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  offer_id BIGINT NOT NULL,
  member_id BIGINT NOT NULL,
  CONSTRAINT uk_reward_offer_target_member UNIQUE (offer_id, member_id)
);

CREATE TABLE IF NOT EXISTS reward_offer_vouchers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  offer_id BIGINT NOT NULL,
  voucher_code VARCHAR(100) NOT NULL,
  is_issued BOOLEAN NOT NULL DEFAULT FALSE,
  issued_to_member_id BIGINT,
  issued_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  reference_id VARCHAR(255),
  CONSTRAINT uk_reward_voucher_code UNIQUE (tenant_id, voucher_code)
);
