-- Reclassify existing BIT rows from vertical-oriented categories to action categories.
-- Run after deploying the matching BitCategory enum update.
BEGIN;

UPDATE reward_bits
SET bit_category = CASE bit_type
    WHEN 'PURCHASE' THEN 'ACCRUAL'
    WHEN 'DINING' THEN 'ACCRUAL'
    WHEN 'ONLINE_ORDER' THEN 'ACCRUAL'
    WHEN 'HOTEL_STAY' THEN 'ACCRUAL'
    WHEN 'FLIGHT_SEGMENT' THEN 'ACCRUAL'
    WHEN 'CAR_RENTAL' THEN 'ACCRUAL'
    WHEN 'REDEMPTION' THEN 'REDEMPTION'
    WHEN 'REWARD_CLAIM' THEN 'REDEMPTION'
    WHEN 'PRIVILEGE_CLAIM' THEN 'PRIVILEGE'
    WHEN 'DEAL' THEN 'DEAL'
    WHEN 'REVERSAL' THEN 'CANCELLATION'
    WHEN 'ENROLL' THEN 'ENROLLMENT'
    WHEN 'PROFILE_UPDATE' THEN 'PROFILE_UPDATE'
    WHEN 'TIER_CHANGE' THEN 'TIER_CHANGE'
    WHEN 'EXPIRATION' THEN 'EXPIRATION'
    WHEN 'CS_ADJUSTMENT' THEN 'SERVICE'
    WHEN 'APP_LOGIN' THEN 'ENGAGEMENT'
    WHEN 'SURVEY' THEN 'ENGAGEMENT'
    WHEN 'REFERRAL' THEN 'ENGAGEMENT'
    WHEN 'SOCIAL_SHARE' THEN 'ENGAGEMENT'
    WHEN 'EVENT' THEN 'ENGAGEMENT'
    WHEN 'PROMO_OFFERS' THEN 'ENGAGEMENT'
    ELSE bit_category
END
WHERE bit_category IN ('COMMERCIAL', 'REDEMPTION', 'TRAVEL', 'REVERSAL', 'SERVICE', 'LIFECYCLE', 'ENGAGEMENT')
   OR bit_type = 'EXPIRATION';

COMMIT;